/******************************************************************************/
/***                Generated by IBExpert 30.06.2025 7:44:18                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/


CREATE GENERATOR GEN_HL_PARAM_ID;

CREATE TABLE HL_PARAM (
    ID          INTEGER NOT NULL,
    TABLO_IP    STR_50 /* STR_50 = VARCHAR(50) */,
    TABLO_PORT  INTEGER,
    BOX_IP      STR_50 /* STR_50 = VARCHAR(50) */,
    BOX_PORT    INTEGER,
    ID_GATE     SMALLINT,
    ID_CAM      SMALLINT,
    ID_DEV      SMALLINT,
    MODE        SMALLINT DEFAULT  0,
    NAME        STR_250 /* STR_250 = VARCHAR(250) */,
    ID_PARKING  SMALLINT,
    IS_ENTER    SMALLINT DEFAULT 1,
    CREATED     TIMESTAMP DEFAULT 'now',
    CHANNEL     INTEGER
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE HL_PARAM ADD CONSTRAINT PK_HL_PARAM PRIMARY KEY (ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;




/* Trigger: HL_PARAM_BI */
CREATE TRIGGER HL_PARAM_BI FOR HL_PARAM
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_hl_param_id,1);
end
^


SET TERM ; ^



/* Fields descriptions */

DESCRIBE FIELD BOX_IP TABLE HL_PARAM
'IP адрес контроллера управления воротами.';

DESCRIBE FIELD BOX_PORT TABLE HL_PARAM
'Port контроллера управления воротами.';

DESCRIBE FIELD CHANNEL TABLE HL_PARAM
'Номер канала в контроллере управления воротами.';

DESCRIBE FIELD CREATED TABLE HL_PARAM
'Дата формирования записи.';

DESCRIBE FIELD ID_CAM TABLE HL_PARAM
'ID видеокамеры системы распознавания регистрационного знака транспортного средства.';

DESCRIBE FIELD ID_DEV TABLE HL_PARAM
'Ссылка на id точки прохода СКУД, связанного с воротами.';

DESCRIBE FIELD ID_GATE TABLE HL_PARAM
'Не используется, резерв.';

DESCRIBE FIELD ID_PARKING TABLE HL_PARAM
'ID паркинга, куда входят ворота.';

DESCRIBE FIELD IS_ENTER TABLE HL_PARAM
'0 - въезд,
1 - выезд.';

DESCRIBE FIELD MODE TABLE HL_PARAM
'Режим работы ворот.
Предполагается, что можно указать различные режимы работы ворот.
';

DESCRIBE FIELD NAME TABLE HL_PARAM
'Название ворот.';

DESCRIBE FIELD TABLO_IP TABLE HL_PARAM
'IP адрес контроллера табло';

DESCRIBE FIELD TABLO_PORT TABLE HL_PARAM
'Port контроллера табло';



/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of procedures */
GRANT SELECT ON HL_PARAM TO PROCEDURE REGISTERPASS_HL_2;
GRANT SELECT ON HL_PARAM TO PROCEDURE VALIDATEPASS_HL_PARKING;
GRANT SELECT ON HL_PARAM TO PROCEDURE VALIDATEPASS_HL_PARKING_2;
GRANT SELECT ON HL_PARAM TO PROCEDURE VALIDATEPASS_HL_PARKING_3;