/******************************************************************************/
/***               Generated by IBExpert 31.03.2025 12:09:32                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE HL_INSIDE (
    ENTERTIME  TIMESTAMP DEFAULT 'now' NOT NULL,
    ID_CARD    VARCHAR(32) NOT NULL,
    COUNTERID  INTEGER NOT NULL
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE HL_INSIDE ADD CONSTRAINT PK_HL_INSIDE PRIMARY KEY (ID_CARD);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of procedures */
GRANT SELECT ON HL_INSIDE TO PROCEDURE VALIDATEPASS_HL_PARKING;
GRANT SELECT ON HL_INSIDE TO PROCEDURE VALIDATEPASS_HL_PARKING_2;